### ISSUE TITLE
motor_control_target() does not work

### ISSUE THREAD

**Issue by enkatsu** [toio/toio.py#4]
I ran examples/motor_control.py but motor_control_target() did not work. Here is the error message to write.

MacBook Air M1, 2020
macOS 13.3.1

```
1: motor_control()
2: motor_control_target()
Traceback (most recent call last):
  File "/Users/enkatsu/Documents/Projects/CollectiveDisplayLayer/motor_control.py", line 108, in <module>
    asyncio.run(main())
  File "/Users/enkatsu/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/enkatsu/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enkatsu/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/enkatsu/Documents/Projects/CollectiveDisplayLayer/motor_control.py", line 102, in main
    await test_motor_2()
  File "/Users/enkatsu/Documents/Projects/CollectiveDisplayLayer/motor_control.py", line 50, in test_motor_2
    await cube.api.motor.register_notification_handler(notification_handler)
  File "/Users/enkatsu/Documents/Projects/CollectiveDisplayLayer/venv/lib/python3.11/site-packages/toio/cube/api/base_class.py", line 124, in register_notification_handler
    await self._register_notification_handler(self._root_notification_handler)
  File "/Users/enkatsu/Documents/Projects/CollectiveDisplayLayer/venv/lib/python3.11/site-packages/toio/cube/api/base_class.py", line 101, in _register_notification_handler
    return await self.interface.register_notification_handler(self.uuid, handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enkatsu/Documents/Projects/CollectiveDisplayLayer/venv/lib/python3.11/site-packages/toio/device_interface/ble.py", line 82, in register_notification_handler
    await self.device.start_notify(char_uuid, notification_handler)
  File "/Users/enkatsu/Documents/Projects/CollectiveDisplayLayer/venv/lib/python3.11/site-packages/bleak/__init__.py", line 717, in start_notify
    await self._backend.start_notify(characteristic, wrapped_callback, **kwargs)
  File "/Users/enkatsu/Documents/Projects/CollectiveDisplayLayer/venv/lib/python3.11/site-packages/bleak/backends/corebluetooth/client.py", line 370, in start_notify
    await self._delegate.start_notifications(characteristic.obj, callback)
  File "/Users/enkatsu/Documents/Projects/CollectiveDisplayLayer/venv/lib/python3.11/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 226, in start_notifications
    await future
bleak.exc.BleakError: Failed to update the notification status for characteristic 16: Error Domain=CBATTErrorDomain Code=6 "The request is not supported." UserInfo={NSLocalizedDescription=The request is not supported.}

Process finished with exit code 1
```

**Comment by TE-KazuhiroYabe** [comment]
@enkatsu 
Thank you for your report.

It is possible that the firmware version of the cube is not up-to-date.

We would like you to try updating the firmware.
https://toio.io/update/app.html


## IMPORTANT NOTE FOR UPDATING

Currently, there are cases where the cube cannot be updated on iOS17 devices. Please use a device with an iOS version earlier than iOS17 to update.
If you are updating on an Android device, there is no problem.

https://toio.io/news/2023/20230922-1.html

**Comment by enkatsu** [comment]
@TE-KazuhiroYabe 
Thanks for your reply :)
I tried updating the firmware using a smartphone with iOS 15. But the same error occurred.

![IMG_9816](https://github.com/toio/toio.py/assets/7820411/6a8b08b5-03bb-43b6-8fac-ff92a3f4a4c6)

**Comment by TE-KazuhiroYabe** [comment]
@enkatsu 

Thank you for trying the firmware update.
Could you please run the following script to get more information?

* check1.py

```python:check1.py
#!/usr/bin/env python

import asyncio
import sys

from bleak import BleakClient
from toio.scanner import BLEScanner


async def print_characteristics():
    cubes = await BLEScanner.scan(1)
    for cube in cubes:
        print("-" * 10, cube.name, "-" * 30)
        async with BleakClient(cube.device) as client:
            await asyncio.sleep(0.5)
            if not client.is_connected:
                print("Failed to connect")
                continue
            for service in client.services:
                print(service.uuid)
                for char in service.characteristics:
                    print(
                        f"  - {char.uuid} (Handle: {char.handle}) | Properties: {char.properties}"
                    )


async def main():
    await print_characteristics()
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
```

Expected result is as folollows:

```
python check1.py
---------- toio Core Cube-xxx ------------------------------
10b20100-5b3b-4571-9508-cf3efcd7bbae
  - 10b20101-5b3b-4571-9508-cf3efcd7bbae (Handle: 12) | Properties: ['read', 'notify']
  - 10b20102-5b3b-4571-9508-cf3efcd7bbae (Handle: 16) | Properties: ['read', 'write-without-response', 'notify']
  - 10b20103-5b3b-4571-9508-cf3efcd7bbae (Handle: 20) | Properties: ['write']
  - 10b20104-5b3b-4571-9508-cf3efcd7bbae (Handle: 23) | Properties: ['write']
  - 10b20106-5b3b-4571-9508-cf3efcd7bbae (Handle: 26) | Properties: ['read', 'write', 'notify']
  - 10b20107-5b3b-4571-9508-cf3efcd7bbae (Handle: 30) | Properties: ['read', 'notify']
  - 10b20108-5b3b-4571-9508-cf3efcd7bbae (Handle: 34) | Properties: ['read', 'notify']
  - 10b201ff-5b3b-4571-9508-cf3efcd7bbae (Handle: 38) | Properties: ['read', 'write', 'notify']
```

**Comment by enkatsu** [comment]
@TE-KazuhiroYabe 

I have run this script. Here is the result.

```
---------- toio Core Cube-p0H ------------------------------
10b20100-5b3b-4571-9508-cf3efcd7bbae
  - 10b20101-5b3b-4571-9508-cf3efcd7bbae (Handle: 12) | Properties: ['read', 'notify']
  - 10b20102-5b3b-4571-9508-cf3efcd7bbae (Handle: 16) | Properties: ['read', 'write-without-response', 'notify']
  - 10b20103-5b3b-4571-9508-cf3efcd7bbae (Handle: 20) | Properties: ['write']
  - 10b20104-5b3b-4571-9508-cf3efcd7bbae (Handle: 23) | Properties: ['write']
  - 10b20106-5b3b-4571-9508-cf3efcd7bbae (Handle: 26) | Properties: ['read', 'write', 'notify']
  - 10b20107-5b3b-4571-9508-cf3efcd7bbae (Handle: 30) | Properties: ['read', 'notify']
  - 10b20108-5b3b-4571-9508-cf3efcd7bbae (Handle: 34) | Properties: ['read', 'notify']
  - 10b201ff-5b3b-4571-9508-cf3efcd7bbae (Handle: 38) | Properties: ['read', 'write', 'notify']
```

**Comment by enkatsu** [comment]
@TE-KazuhiroYabe 

I ran motor_control_target() again after charging the toio cube and it worked fine. is it possible that the low charge level of the toio cube was the cause?

**Comment by TE-KazuhiroYabe** [comment]
@enkatsu 
I feel glad your cube is working.

I do not think the low battery is the cause of this issue.
Many operating systems keep bluetooth device information internally and may not update the internal information when the cube firmware is updated.
There is no published way to manually update the internal information in many cases, but restarting the computer or turning the bluetooth function on and off may update it.

I apologize for not being able to provide accurate information.

**Comment by enkatsu** [comment]
I think I've learned a lot.
This Issue has been resolved and is closed.

Thank you for your polite response :)
